FROM centos:7

USER root

# install php8
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm \
    && yum -y install yum-utils yum-utils \
    && yum-config-manager --disable 'remi-php*' \
    && yum-config-manager --enable remi-php81 \
    && yum repolist \
    && yum -y install php php-{cli,fpm,mysqlnd,zip,devel,gd,mbstring,curl,xml,pear,bcmath,json,opcache,redis,memcache}

RUN yum install -y epel-release
RUN yum install -y openvpn sed git openssl mysql

WORKDIR /root
RUN git clone https://github.com/nguyenngoctranvu/OpenVPN-Admin
WORKDIR /root/OpenVPN-Admin
RUN cp -r "./installation/scripts" "/etc/openvpn/" && chmod +x "/etc/openvpn/scripts/"* && \
    cp "./installation/server.conf" "/etc/openvpn/" && mkdir "/etc/openvpn/ccd"


# change group nogroup to group nobody
RUN sed -i "s/group nogroup/group nobody/" "/etc/openvpn/server.conf" && \
    sed -i "s/explicit-exit-notify 1/explicit-exit-notify 0/" "/etc/openvpn/server.conf"

# Get the rsa keys
WORKDIR /root/
RUN curl -L "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.6/EasyRSA-unix-v3.0.6.tgz" -O && \
    tar -xaf "EasyRSA-unix-v3.0.6.tgz" && mv "EasyRSA-v3.0.6" /etc/openvpn/easy-rsa &&rm "EasyRSA-unix-v3.0.6.tgz"

COPY ./openvpn/docker-entrypoint.sh /usr/local/bin

# Make ip forwading and make it persistent
RUN echo "net.ipv4.ip_forward = 1" >> "/etc/sysctl.conf"

ENTRYPOINT ["docker-entrypoint.sh"]
